### ISSUE TITLE
Have the diaries collapsed initially with the ability to expand and collapse.

### ISSUE THREAD

**Issue by almccon** [americanpanorama/panorama-overlandtrails#7]

**Comment by ebrelsford** [comment]
@almccon like this, right (with a different icon)?

![trails-expand](https://cloud.githubusercontent.com/assets/375002/14218162/869bd742-f820-11e5-9c2e-b68625b842fb.gif)

**Comment by almccon** [comment]
Yeah!

**Comment by ebrelsford** [comment]
@almccon I didn't notice this earlier, but when the diaries are all collapsed, the last page of diaries don't get highlighted on the map. This is because the code checks to see if the diary is a the top and highlights it. If a diary is never at the top it is never highlighted on the map.

Should I go ahead with how this is implemented now and create a separate issue for that? Or how else might you like to handle this situation?

![trails-path](https://cloud.githubusercontent.com/assets/375002/14464301/45c092d8-009c-11e6-9f83-2f1ef3f913ab.gif)

**Comment by almccon** [comment]
Ugh, that's tricky. Let's create a new issue for it. Not sure of the right solution. Do we need some kind of whitespace to allow you to scroll all the way down so that the final collapsed entry is at the top? Feels like there's gotta be a saner way.

**Comment by ebrelsford** [comment]
Yeah I thought about adding whitespace at the bottom but it feels pretty hacky. I'll finish this as-is and add a new issue.
